name: Cute Map

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      id-token: write # to verify the deployment originates from an appropriate
      pages: write # to deploy to Pages
      contents: read # to checkout private repositories
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Upload Pages Artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: . # Upload all files from the repository root directory
      - uses: actions/deploy-pages@v4
        id: deployment
